module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src'],
  testMatch: ['**/__tests__/**/*.ts', '**/*.test.ts', '**/*.spec.ts'],
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.d.ts',
    '!src/**/__tests__/**',
    '!src/**/index.ts',
  ],
  coverageThreshold: {
    global: {
      branches: 70,
      functions: 70,
      lines: 70,
      statements: 70,
    },
  },
  coverageDirectory: '<rootDir>/coverage',
  moduleNameMapper: {
    '^@monorepo/shared$': '<rootDir>/../../packages/shared/src',
    '^@monorepo/shared/(.*)$': '<rootDir>/../../packages/shared/src/$1',
    '^@monorepo/config$': '<rootDir>/../../packages/config/src',
    '^@monorepo/config/(.*)$': '<rootDir>/../../packages/config/src/$1',
    '^@monorepo/test-utils$': '<rootDir>/../../packages/test-utils/src',
    '^@monorepo/test-utils/(.*)$': '<rootDir>/../../packages/test-utils/src/$1',
    '^@monorepo/database$': '<rootDir>/../../packages/database/src',
    '^@monorepo/database/(.*)$': '<rootDir>/../../packages/database/src/$1',
    '^@monorepo/monitoring$': '<rootDir>/../../packages/monitoring/src',
    '^@monorepo/monitoring/(.*)$': '<rootDir>/../../packages/monitoring/src/$1',
    '^@monorepo/rate-limit$': '<rootDir>/../../packages/rate-limit/src',
    '^@monorepo/rate-limit/(.*)$': '<rootDir>/../../packages/rate-limit/src/$1',
  },
  transform: {
    '^.+\\.ts$': [
      'ts-jest',
      {
        tsconfig: {
          esModuleInterop: true,
          skipLibCheck: true,
          baseUrl: '.',
          paths: {
            '@monorepo/shared': ['../../packages/shared/src'],
            '@monorepo/shared/*': ['../../packages/shared/src/*'],
            '@monorepo/config': ['../../packages/config/src'],
            '@monorepo/config/*': ['../../packages/config/src/*'],
            '@monorepo/test-utils': ['../../packages/test-utils/src'],
            '@monorepo/test-utils/*': ['../../packages/test-utils/src/*'],
            '@monorepo/database': ['../../packages/database/src'],
            '@monorepo/database/*': ['../../packages/database/src/*'],
            '@monorepo/monitoring': ['../../packages/monitoring/src'],
            '@monorepo/monitoring/*': ['../../packages/monitoring/src/*'],
            '@monorepo/rate-limit': ['../../packages/rate-limit/src'],
            '@monorepo/rate-limit/*': ['../../packages/rate-limit/src/*'],
          },
        },
      },
    ],
  },
};
